remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/logo.png
title: Coining Reason
description: <p>Hosted by <strong>Neta DAO</strong><br><br>The Community Accelerator - Funding collaboration, growth and innovation around NETA</p><a href="https://netadao.zone">https://netadao.zone</a>

