remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
#logo: /assets/img/logo.png
layout: default
title: Coining Reason
description: Neta DAO Academy is an educational subDAO with a focus on research and outreach.
