remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
logo: /assets/img/logo.png
title: Coining Reason
description: The Neta DAO Academy is a subDAO focused on research and educational outreach.
