remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
logo: /assets/img/logo.png
title: Coining Reason
description: <p>Hosted by <a href="https://netadao.zone"><strong>Neta DAO</strong></a><br><br>Neta DAO is a nonprofit community accelerator and public institution for Juno and the Interchain. Become a member by joining <a href="https://daodao.zone/dao/juno1c5v6jkmre5xa9vf9aas6yxewc7aqmjy0rlkkyk4d88pnwuhclyhsrhhns6">Neta DAO on DAO DAO</a><br><br>Neta DAO Academy is an educational subDAO with a focus on research and outreach.</p>
