remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Coining Reason
description: <a href="https://netadao.zone">https://netadao.zone</a><br><p>Hosted by <strong>Neta DAO</strong><br><br>The Community Accelerator - Funding collaboration, growth and innovation around NETA</p>

